### ISSUE TITLE
Workshop 2402: changed branch name to standard abbreviation

### ISSUE THREAD

**Issue by wmotion** [4TUResearchData-Carpentries/workshop_notes#17]
Dear fellow instructors/issue assignees,

I have created a new branch with *SCW* for Software Carpentry Workshop in the name, in lieu of SWC. An oft-recurring glitch. 

For consistency with the previous editions, please let's use
https://github.com/4TUResearchData-Carpentries/workshop_notes/tree/2402-SCW-TUD (SCW)
instead of
https://github.com/4TUResearchData-Carpentries/workshop_notes/tree/2402-SWC-TUD (SWC)

You appeared to have tested the previous branch. I trust that the adjustments should be minimal and I hope this is not too inconvenient. A point to restart from could be:

    git clone git@github.com:4TUResearchData-Carpentries/workshop_notes.git --branch 2402-SCW-TUD --single-branch [your directory name of choice]

I leave it to you to delete the old branch, when you feel to have transitioned to the new name.
Thank you for your collaboration.

**Comment by mwakok** [comment]
Thanks for the update @wmotion. I wasn't aware there is a preferential naming convention, I see both versions used by the Carpentries. I will delete the branch.

@wmotion Could you also update the README in the master branch, it mentions "SWC" a couple of times.

**Comment by wmotion** [comment]
@mwakok Thanks in turn for the suggestions. I aimed to iron out those kinks with https://github.com/4TUResearchData-Carpentries/workshop_notes/commit/2a9eb20bba5bd81547dfc813df4097194fe0b656

I have seen that the old branch 2402-SWC-TUD has been deleted and take it a sign to close the issue.

**Comment by wmotion** [comment]
Oops... I thought to have seen that the old branch had been deleted. Therefore, I do not close this issue. Sorry for the positive differential of entropy

**Comment by mwakok** [comment]
I have deleted the branch.
